
- id: "motion_camera_alert"
  alias: "–¢–µ—Å—Ç–æ–≤–∞—è –∞–≤—Ç–æ–º–∞—Ç–∏–∑–∞—Ü–∏—è"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: persistent_notification.create
      data:
        message: "Home Assistant –∑–∞–ø—É—â–µ–Ω!"
        title: "–¢–µ—Å—Ç"


- id: "motion_camera_alert"
  alias: "–û—Ç–ø—Ä–∞–≤–∫–∞ —Ñ–æ—Ç–æ –ø—Ä–∏ –¥–≤–∏–∂–µ–Ω–∏–∏ –∫–∞–º–µ—Ä—ã"
  description: "–ê–≤—Ç–æ–º–∞—Ç–∏—á–µ—Å–∫–∞—è –æ—Ç–ø—Ä–∞–≤–∫–∞ —Ñ–æ—Ç–æ –ø—Ä–∏ –æ–±–Ω–∞—Ä—É–∂–µ–Ω–∏–∏ –¥–≤–∏–∂–µ–Ω–∏—è –∫–∞–º–µ—Ä–æ–π"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: camera.chuangmi_026c02_7a2a_motion_event
  action:
    - service: script.hallway_camera_snapshot_send
    - delay: "00:00:05"
    - service: telegram_bot.send_message
      data:
        message: "üö∂ –û–±–Ω–∞—Ä—É–∂–µ–Ω–æ –¥–≤–∏–∂–µ–Ω–∏–µ –∫–∞–º–µ—Ä–æ–π!"
        chat_id: 813740593


- id: "motion_camera_alert Street"
  alias: "–û—Ç–ø—Ä–∞–≤–∫–∞ —Ñ–æ—Ç–æ –ø—Ä–∏ –æ—Ç–∫—Ä—ã—Ç–∏–∏ –∫–∞–ª–∏—Ç–∫–∏"
  description: "–ê–≤—Ç–æ–º–∞—Ç–∏—á–µ—Å–∫–∞—è –æ—Ç–ø—Ä–∞–≤–∫–∞ —Ñ–æ—Ç–æ –ø—Ä–∏ –æ—Ç–∫—Ä—ã—Ç–∏–∏ –∫–∞–ª–∏—Ç–∫–∏"
  trigger:
    - platform: event
      event_type:
      event_data:
        entity_id: camera.192_168_0_112
  action:
    - service: script.hallway_camera_snapshot_send
    - delay: "00:00:05"
    - service: telegram_bot.send_message
      data:
        message: "üö∂ –û–±–Ω–∞—Ä—É–∂–µ–Ω–æ –¥–≤–∏–∂–µ–Ω–∏–µ –∫–∞–º–µ—Ä–æ–π!"
        chat_id: 813740593

