default_config:

# Автоматизации будут загружены из отдельного файла
automation: !include automations.yaml

# Фронтенд и темы
frontend:
  themes: !include_dir_merge_named themes

# Скрипты
script: !include scripts.yaml

# Сцены
scene: !include scenes.yaml

# HTTP настройки
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.192.0/24
    - 127.0.0.1/32
    - ::1/128
  ip_ban_enabled: false
  login_attempts_threshold: 10
  cors_allowed_origins:
    - https://cast.home-assistant.io

# Telegram бот
telegram_bot:
  - platform: polling
    api_key: "8364524814:AAHUjHw3e9H3ATouGOzs3yafJtPwidBqSRE"
    allowed_chat_ids:
      - 813740593

# Уведомления
notify:
  - name: notify.telegram
    platform: telegram
    chat_id: 813740593

# Основные настройки Home Assistant
homeassistant:
  allowlist_external_dirs:
    - /config/camera_photos
